//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeiHi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Add
    {
        public long AddId { get; set; }
        public string Url { get; set; }
        public string Title { get; set; }
        public Nullable<bool> Avaliable { get; set; }
        public System.DateTime DateCreated { get; set; }
    }
}
