//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeiHi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public Role()
        {
            this.AdminRole = new HashSet<AdminRole>();
            this.RolePermission = new HashSet<RolePermission>();
        }
    
        public int RoleId { get; set; }
        public string Name { get; set; }
        public Nullable<int> ParentRoleId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
    
        public virtual ICollection<AdminRole> AdminRole { get; set; }
        public virtual ICollection<RolePermission> RolePermission { get; set; }
    }
}
