//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeiHi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public Service()
        {
            this.Booking = new HashSet<Booking>();
            this.UserComments = new HashSet<UserComments>();
            this.UserFavorites = new HashSet<UserFavorites>();
        }
    
        public long ServiceId { get; set; }
        public int ServiceTypeId { get; set; }
        public long ShopId { get; set; }
        public string TitleUrl { get; set; }
        public string Title { get; set; }
        public string Detail { get; set; }
        public decimal CMUnitCost { get; set; }
        public decimal OriginalUnitCost { get; set; }
        public string Designer { get; set; }
        public Nullable<bool> IfSupportRealTimeRefund { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
    
        public virtual ICollection<Booking> Booking { get; set; }
        public virtual ServiceType ServiceType { get; set; }
        public virtual Shop Shop { get; set; }
        public virtual ICollection<UserComments> UserComments { get; set; }
        public virtual ICollection<UserFavorites> UserFavorites { get; set; }
    }
}
