//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeiHi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopUser
    {
        public long ShopUserId { get; set; }
        public string Password { get; set; }
        public long ShopId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
        public string ShopUserName { get; set; }
        public string AliPayAccount { get; set; }
        public string FullName { get; set; }
        public string WeiXinPayAccount { get; set; }
    
        public virtual Shop Shop { get; set; }
    }
}
