//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeiHi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop
    {
        public Shop()
        {
            this.Booking = new HashSet<Booking>();
            this.ProductBrand = new HashSet<ProductBrand>();
            this.Service = new HashSet<Service>();
            this.ShopBrandImages = new HashSet<ShopBrandImages>();
            this.ShopUser = new HashSet<ShopUser>();
            this.UserComments = new HashSet<UserComments>();
            this.UserFavorites = new HashSet<UserFavorites>();
        }
    
        public long ShopId { get; set; }
        public string DetailAddress { get; set; }
        public int RegionID { get; set; }
        public Nullable<long> ParentShopId { get; set; }
        public string Phone { get; set; }
        public string Contract { get; set; }
        public bool IsOnline { get; set; }
        public string PurchaseNotes { get; set; }
        public string Coordinates { get; set; }
        public bool IsHot { get; set; }
        public string ShopTag { get; set; }
        public string Comment { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
        public string Title { get; set; }
        public Nullable<int> StreetId { get; set; }
    
        public virtual ICollection<Booking> Booking { get; set; }
        public virtual ICollection<ProductBrand> ProductBrand { get; set; }
        public virtual RecommandShop RecommandShop { get; set; }
        public virtual Region Region { get; set; }
        public virtual ICollection<Service> Service { get; set; }
        public virtual ICollection<ShopBrandImages> ShopBrandImages { get; set; }
        public virtual ICollection<ShopUser> ShopUser { get; set; }
        public virtual ICollection<UserComments> UserComments { get; set; }
        public virtual ICollection<UserFavorites> UserFavorites { get; set; }
        public virtual Region Region1 { get; set; }
    }
}
