//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeiHi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Booking = new HashSet<Booking>();
            this.UserComments = new HashSet<UserComments>();
            this.UserFavorites = new HashSet<UserFavorites>();
        }
    
        public long UserId { get; set; }
        public string Mobile { get; set; }
        public string FullName { get; set; }
        public string Salt { get; set; }
        public Nullable<int> Gender { get; set; }
        public string ProfilePhoto { get; set; }
        public decimal Balance { get; set; }
        public string Device { get; set; }
        public string Version { get; set; }
        public Nullable<int> DownloadFromApplicationId { get; set; }
        public Nullable<int> HairOfLegth { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> BirthDay { get; set; }
        public string Token { get; set; }
        public string VerifyCode { get; set; }
        public bool IsLogin { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
    
        public virtual ICollection<Booking> Booking { get; set; }
        public virtual ICollection<UserComments> UserComments { get; set; }
        public virtual ICollection<UserFavorites> UserFavorites { get; set; }
    }
}
