//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeiHi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserFavorites
    {
        public long UserFavoritesId { get; set; }
        public long UserId { get; set; }
        public Nullable<long> ShopId { get; set; }
        public Nullable<long> ServiceId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
    
        public virtual Service Service { get; set; }
        public virtual Shop Shop { get; set; }
        public virtual User User { get; set; }
    }
}
