//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeiHi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserComments
    {
        public UserComments()
        {
            this.UserCommentsReply = new HashSet<UserCommentsReply>();
        }
    
        public long UserCommentId { get; set; }
        public long ShopId { get; set; }
        public long UserId { get; set; }
        public Nullable<bool> Display { get; set; }
        public long ServiceId { get; set; }
        public string ServiceName { get; set; }
        public int Rate { get; set; }
        public string Comment { get; set; }
        public Nullable<long> UserCommentSharedImgID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
    
        public virtual Service Service { get; set; }
        public virtual Shop Shop { get; set; }
        public virtual User User { get; set; }
        public virtual UserCommentSharedImg UserCommentSharedImg { get; set; }
        public virtual ICollection<UserCommentsReply> UserCommentsReply { get; set; }
    }
}
