//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeiHi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSuggest
    {
        public long UserSuggestId { get; set; }
        public string Content { get; set; }
        public string Contract { get; set; }
        public System.DateTime DateCreated { get; set; }
    }
}
