//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChouMei.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityJob
    {
        public ActivityJob()
        {
            this.ActivityJobApplies = new HashSet<ActivityJobApply>();
            this.ActivityJobComplains = new HashSet<ActivityJobComplain>();
        }
    
        public long JobId { get; set; }
        public Nullable<long> CompanyId { get; set; }
        public string CompanyName { get; set; }
        public string Title { get; set; }
        public int JobTypeId { get; set; }
        public int StatusId { get; set; }
        public int PositionId { get; set; }
        public int RegionId { get; set; }
        public Nullable<int> WageUnitId { get; set; }
        public Nullable<decimal> Wage { get; set; }
        public bool IncludeDinner { get; set; }
        public bool IncludeRoom { get; set; }
        public bool IncludeCommission { get; set; }
        public Nullable<int> TermId { get; set; }
        public int Gender { get; set; }
        public decimal Deposit { get; set; }
        public Nullable<int> PeopleRequired { get; set; }
        public string Contact { get; set; }
        public string ContactPhone { get; set; }
        public string Address { get; set; }
        public System.DateTime DateFrom { get; set; }
        public System.DateTime DateExpiry { get; set; }
        public Nullable<System.DateTime> WorkFrom { get; set; }
        public Nullable<System.DateTime> WorkEnd { get; set; }
        public string Description { get; set; }
        public int ViewTimes { get; set; }
        public int FakeViewTimes { get; set; }
        public int Shares { get; set; }
        public int WapViewTimes { get; set; }
        public bool Recommended { get; set; }
        public bool Sticky { get; set; }
        public Nullable<System.DateTime> StickyExpired { get; set; }
        public bool Disabled { get; set; }
        public bool Reptile { get; set; }
        public string SourceWebSite { get; set; }
        public bool MonMorning { get; set; }
        public bool MonAfternoon { get; set; }
        public bool MonNight { get; set; }
        public bool TueMorning { get; set; }
        public bool TueAfternoon { get; set; }
        public bool TueNight { get; set; }
        public bool WedMorning { get; set; }
        public bool WedAfternoon { get; set; }
        public bool WedNight { get; set; }
        public bool ThuMorning { get; set; }
        public bool ThuAfternoon { get; set; }
        public bool ThuNight { get; set; }
        public bool FriMorning { get; set; }
        public bool FriAfternoon { get; set; }
        public bool FriNight { get; set; }
        public bool SatMorning { get; set; }
        public bool SatAfternoon { get; set; }
        public bool SatNight { get; set; }
        public bool SunMorning { get; set; }
        public bool SunAfternoon { get; set; }
        public bool SunNight { get; set; }
        public bool IgnoreTimeSheet { get; set; }
        public Nullable<System.DateTime> DatePublished { get; set; }
        public Nullable<int> AgentUserId { get; set; }
        public Nullable<int> AdminId { get; set; }
        public Nullable<int> JobAllocateTypeId { get; set; }
        public Nullable<System.DateTime> DateEmployeeManagementDeleted { get; set; }
        public Nullable<System.DateTime> DateDeleted { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
    
        public virtual ActivityJobPosition ActivityJobPosition { get; set; }
        public virtual Company Company { get; set; }
        public virtual JobStatu JobStatu { get; set; }
        public virtual JobType JobType { get; set; }
        public virtual Region Region { get; set; }
        public virtual Term Term { get; set; }
        public virtual WageUnit WageUnit { get; set; }
        public virtual ICollection<ActivityJobApply> ActivityJobApplies { get; set; }
        public virtual ICollection<ActivityJobComplain> ActivityJobComplains { get; set; }
    }
}
