//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChouMei.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdvertisingPage
    {
        public AdvertisingPage()
        {
            this.AdvertisingPositions = new HashSet<AdvertisingPosition>();
        }
    
        public int PageId { get; set; }
        public int ApplicationId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual ICollection<AdvertisingPosition> AdvertisingPositions { get; set; }
    }
}
