//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChouMei.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advertising
    {
        public int AdvertisingId { get; set; }
        public int PositionId { get; set; }
        public Nullable<int> TypeId { get; set; }
        public string Title { get; set; }
        public string ImagePath { get; set; }
        public string NavImagePath { get; set; }
        public string Link { get; set; }
        public Nullable<long> JobId { get; set; }
        public Nullable<int> JobTypeId { get; set; }
        public System.DateTime DateFrom { get; set; }
        public System.DateTime DateTo { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
    
        public virtual AdvertisingPosition AdvertisingPosition { get; set; }
    }
}
