//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChouMei.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgentPermission
    {
        public AgentPermission()
        {
            this.AgentRoleAgentPermissions = new HashSet<AgentRoleAgentPermission>();
            this.AgentUserAgentPermissions = new HashSet<AgentUserAgentPermission>();
            this.AgentUserTypeAgentPermissions = new HashSet<AgentUserTypeAgentPermission>();
        }
    
        public int PermissionId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Group { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
    
        public virtual ICollection<AgentRoleAgentPermission> AgentRoleAgentPermissions { get; set; }
        public virtual ICollection<AgentUserAgentPermission> AgentUserAgentPermissions { get; set; }
        public virtual ICollection<AgentUserTypeAgentPermission> AgentUserTypeAgentPermissions { get; set; }
    }
}
