//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChouMei.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgentUser
    {
        public AgentUser()
        {
            this.AgentUserAgentRoles = new HashSet<AgentUserAgentRole>();
            this.AgentUserLogons = new HashSet<AgentUserLogon>();
            this.AgentUserAgentPermissions = new HashSet<AgentUserAgentPermission>();
            this.AgentUserRegions = new HashSet<AgentUserRegion>();
        }
    
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Salt { get; set; }
        public Nullable<System.DateTime> LastLogonDate { get; set; }
        public Nullable<int> AdminAgentUserId { get; set; }
        public int TypeId { get; set; }
        public Nullable<int> PromoterId { get; set; }
        public Nullable<System.DateTime> DateDeleted { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
    
        public virtual AgentUserType AgentUserType { get; set; }
        public virtual Promoter Promoter { get; set; }
        public virtual ICollection<AgentUserAgentRole> AgentUserAgentRoles { get; set; }
        public virtual ICollection<AgentUserLogon> AgentUserLogons { get; set; }
        public virtual ICollection<AgentUserAgentPermission> AgentUserAgentPermissions { get; set; }
        public virtual ICollection<AgentUserRegion> AgentUserRegions { get; set; }
    }
}
