//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChouMei.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgentUserAgentRole
    {
        public int UserId { get; set; }
        public int RoleId { get; set; }
        public System.DateTime DateCreatd { get; set; }
    
        public virtual AgentRole AgentRole { get; set; }
        public virtual AgentUser AgentUser { get; set; }
    }
}
