//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChouMei.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplyStatu
    {
        public ApplyStatu()
        {
            this.ActivityJobApplies = new HashSet<ActivityJobApply>();
            this.CampusJobApplies = new HashSet<CampusJobApply>();
            this.InternJobApplies = new HashSet<InternJobApply>();
            this.ServiceJobApplies = new HashSet<ServiceJobApply>();
            this.TutorJobApplies = new HashSet<TutorJobApply>();
        }
    
        public int StatusId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual ICollection<ActivityJobApply> ActivityJobApplies { get; set; }
        public virtual ICollection<CampusJobApply> CampusJobApplies { get; set; }
        public virtual ICollection<InternJobApply> InternJobApplies { get; set; }
        public virtual ICollection<ServiceJobApply> ServiceJobApplies { get; set; }
        public virtual ICollection<TutorJobApply> TutorJobApplies { get; set; }
    }
}
