//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChouMei.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CampusJobApply
    {
        public long ApplyId { get; set; }
        public long JobId { get; set; }
        public long UserId { get; set; }
        public int StatusId { get; set; }
        public Nullable<System.DateTime> DateHired { get; set; }
        public Nullable<System.DateTime> DateEnded { get; set; }
        public Nullable<int> DateEndedReasonId { get; set; }
        public Nullable<System.DateTime> DateDeleted { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
    
        public virtual ApplyStatu ApplyStatu { get; set; }
        public virtual CampusJob CampusJob { get; set; }
        public virtual User User { get; set; }
    }
}
