//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChouMei.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComplainStatu
    {
        public ComplainStatu()
        {
            this.ActivityJobComplains = new HashSet<ActivityJobComplain>();
            this.CampusJobComplains = new HashSet<CampusJobComplain>();
            this.InternJobComplains = new HashSet<InternJobComplain>();
            this.ServiceJobComplains = new HashSet<ServiceJobComplain>();
            this.TutorJobComplains = new HashSet<TutorJobComplain>();
        }
    
        public int StatusId { get; set; }
        public string Name { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual ICollection<ActivityJobComplain> ActivityJobComplains { get; set; }
        public virtual ICollection<CampusJobComplain> CampusJobComplains { get; set; }
        public virtual ICollection<InternJobComplain> InternJobComplains { get; set; }
        public virtual ICollection<ServiceJobComplain> ServiceJobComplains { get; set; }
        public virtual ICollection<TutorJobComplain> TutorJobComplains { get; set; }
    }
}
