//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChouMei.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public Company()
        {
            this.ActivityJobs = new HashSet<ActivityJob>();
            this.CampusJobs = new HashSet<CampusJob>();
            this.CompanyCashFlows = new HashSet<CompanyCashFlow>();
            this.CompanyLogons = new HashSet<CompanyLogon>();
            this.CompanyCashIns = new HashSet<CompanyCashIn>();
            this.InternJobs = new HashSet<InternJob>();
            this.ServiceJobs = new HashSet<ServiceJob>();
            this.TutorJobs = new HashSet<TutorJob>();
        }
    
        public long CompanyId { get; set; }
        public Nullable<int> RegionId { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string FullName { get; set; }
        public string PendingFullName { get; set; }
        public string Contact { get; set; }
        public string Password { get; set; }
        public string Salt { get; set; }
        public string PaymentPassword { get; set; }
        public string PaymentSalt { get; set; }
        public string Address { get; set; }
        public string LicensePhoto { get; set; }
        public string AgentPhoto { get; set; }
        public string Longitude { get; set; }
        public string Latitude { get; set; }
        public string Introduction { get; set; }
        public bool Status { get; set; }
        public bool Verified { get; set; }
        public decimal Balance { get; set; }
        public string Device { get; set; }
        public string DeviceToken { get; set; }
        public string BaiduUserId { get; set; }
        public string Version { get; set; }
        public Nullable<int> DownloadFromApplicationId { get; set; }
        public bool VoiceAlert { get; set; }
        public bool Vibrate { get; set; }
        public bool IsLogin { get; set; }
        public int NotificationCount { get; set; }
        public Nullable<int> AgentUserId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
    
        public virtual ICollection<ActivityJob> ActivityJobs { get; set; }
        public virtual ICollection<CampusJob> CampusJobs { get; set; }
        public virtual ICollection<CompanyCashFlow> CompanyCashFlows { get; set; }
        public virtual ICollection<CompanyLogon> CompanyLogons { get; set; }
        public virtual ICollection<CompanyCashIn> CompanyCashIns { get; set; }
        public virtual ICollection<InternJob> InternJobs { get; set; }
        public virtual ICollection<ServiceJob> ServiceJobs { get; set; }
        public virtual ICollection<TutorJob> TutorJobs { get; set; }
    }
}
