//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChouMei.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyCashIn
    {
        public long CashInId { get; set; }
        public long CompanyId { get; set; }
        public Nullable<long> TradeId { get; set; }
        public decimal Amount { get; set; }
        public Nullable<System.DateTime> DatePaid { get; set; }
        public Nullable<System.DateTime> DatePaymentConfirmed { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
