//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChouMei.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyLogon
    {
        public long LogonId { get; set; }
        public long CompanyId { get; set; }
        public string Token { get; set; }
        public System.DateTime TokenExpiryDate { get; set; }
        public string IPAddress { get; set; }
        public System.DateTime DateLogon { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
