//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChouMei.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyCashFlow
    {
        public long FlowId { get; set; }
        public long CompanyId { get; set; }
        public decimal Balance { get; set; }
        public decimal Payment { get; set; }
        public int FlowTypeId { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual CompanyCashFlowType CompanyCashFlowType { get; set; }
    }
}
