//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChouMei.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Date
    {
        public int DateId { get; set; }
        public System.DateTime Date1 { get; set; }
        public int Year { get; set; }
        public int Month { get; set; }
        public string MonthName { get; set; }
        public int DayInYear { get; set; }
        public int DayInMonth { get; set; }
        public int DayInWeek { get; set; }
        public string DayName { get; set; }
        public int WeekNumber { get; set; }
        public System.DateTime DateCreated { get; set; }
    }
}
