//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChouMei.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventLog
    {
        public long LogId { get; set; }
        public long UserId { get; set; }
        public int EventId { get; set; }
        public bool Finished { get; set; }
        public Nullable<decimal> Bonus { get; set; }
        public System.DateTime DateCreated { get; set; }
    }
}
