//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChouMei.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FilterWorkTime
    {
        public long UserId { get; set; }
        public bool MonMorning { get; set; }
        public bool MonAfternoon { get; set; }
        public bool MonNight { get; set; }
        public bool TueMorning { get; set; }
        public bool TueAfternoon { get; set; }
        public bool TueNight { get; set; }
        public bool WedMorning { get; set; }
        public bool WedAfternoon { get; set; }
        public bool WedNight { get; set; }
        public bool ThuMorning { get; set; }
        public bool ThuAfternoon { get; set; }
        public bool ThuNight { get; set; }
        public bool FriMorning { get; set; }
        public bool FriAfternoon { get; set; }
        public bool FriNight { get; set; }
        public bool SatMorning { get; set; }
        public bool SatAfternoon { get; set; }
        public bool SatNight { get; set; }
        public bool SunMorning { get; set; }
        public bool SunAfternoon { get; set; }
        public bool SunNight { get; set; }
        public System.DateTime DateCreated { get; set; }
    }
}
