//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChouMei.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobType
    {
        public JobType()
        {
            this.ActivityJobs = new HashSet<ActivityJob>();
            this.CampusJobs = new HashSet<CampusJob>();
            this.InternJobs = new HashSet<InternJob>();
            this.ServiceJobs = new HashSet<ServiceJob>();
            this.TutorJobs = new HashSet<TutorJob>();
        }
    
        public int TypeId { get; set; }
        public string Name { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual ICollection<ActivityJob> ActivityJobs { get; set; }
        public virtual ICollection<CampusJob> CampusJobs { get; set; }
        public virtual ICollection<InternJob> InternJobs { get; set; }
        public virtual ICollection<ServiceJob> ServiceJobs { get; set; }
        public virtual ICollection<TutorJob> TutorJobs { get; set; }
    }
}
