//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChouMei.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public long MessageId { get; set; }
        public long SendingId { get; set; }
        public long TargetId { get; set; }
        public long JobId { get; set; }
        public int JobTypeId { get; set; }
        public string Message1 { get; set; }
        public int MessageTypeId { get; set; }
        public bool Read { get; set; }
        public Nullable<int> SystemMessageId { get; set; }
        public Nullable<System.DateTime> DateDeleted { get; set; }
        public System.DateTime DateCreated { get; set; }
    }
}
