//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChouMei.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public long NotificationId { get; set; }
        public long MessageId { get; set; }
        public string MessageType { get; set; }
        public int MessageTypeId { get; set; }
        public string Message { get; set; }
        public string MessageTitle { get; set; }
        public long SendingId { get; set; }
        public long TargetId { get; set; }
        public long JobId { get; set; }
        public int JobTypeId { get; set; }
        public string Device { get; set; }
        public string DeviceToken { get; set; }
        public string BaiduUserId { get; set; }
        public bool VoiceAlert { get; set; }
        public bool Vibrate { get; set; }
        public int NotificationCount { get; set; }
        public System.DateTime DateCreated { get; set; }
    }
}
