//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChouMei.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.OrderLines = new HashSet<OrderLine>();
            this.Trades = new HashSet<Trade>();
        }
    
        public long OrderId { get; set; }
        public string OrderNumber { get; set; }
        public long CompanyId { get; set; }
        public long JobId { get; set; }
        public int JobTypeId { get; set; }
        public string Title { get; set; }
        public System.DateTime Date { get; set; }
        public int PeopleCount { get; set; }
        public decimal Amount { get; set; }
        public Nullable<decimal> UpdatedAmount { get; set; }
        public Nullable<System.DateTime> DatePaid { get; set; }
        public Nullable<System.DateTime> DatePaymentConfirmed { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
    
        public virtual ICollection<OrderLine> OrderLines { get; set; }
        public virtual ICollection<Trade> Trades { get; set; }
    }
}
