//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChouMei.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentNotify
    {
        public long payment_id { get; set; }
        public string notify_time { get; set; }
        public string notify_type { get; set; }
        public string notify_id { get; set; }
        public string sign_type { get; set; }
        public string sign { get; set; }
        public string out_trade_no { get; set; }
        public string subject { get; set; }
        public string payment_type { get; set; }
        public string trade_no { get; set; }
        public string trade_status { get; set; }
        public string seller_id { get; set; }
        public string seller_email { get; set; }
        public string buyer_id { get; set; }
        public string buyer_email { get; set; }
        public string total_fee { get; set; }
        public string quantity { get; set; }
        public string price { get; set; }
        public string body { get; set; }
        public string gmt_create { get; set; }
        public string gmt_payment { get; set; }
        public string is_total_fee_adjust { get; set; }
        public string use_coupon { get; set; }
        public string discount { get; set; }
        public string refund_status { get; set; }
        public string gmt_refund { get; set; }
        public string note { get; set; }
        public System.DateTime date_created { get; set; }
    }
}
