//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChouMei.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promoter
    {
        public Promoter()
        {
            this.AgentUsers = new HashSet<AgentUser>();
            this.PromoterTeams = new HashSet<PromoterTeam>();
        }
    
        public int PromoterId { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Salt { get; set; }
        public Nullable<System.DateTime> LastLogonDate { get; set; }
        public Nullable<int> CreatedByAdminId { get; set; }
        public Nullable<int> CreatedByAgentUserId { get; set; }
        public Nullable<System.DateTime> DateDeleted { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
    
        public virtual ICollection<AgentUser> AgentUsers { get; set; }
        public virtual ICollection<PromoterTeam> PromoterTeams { get; set; }
    }
}
