//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChouMei.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Region
    {
        public Region()
        {
            this.ActivityJobs = new HashSet<ActivityJob>();
            this.AgentUserRegions = new HashSet<AgentUserRegion>();
            this.CampusJobs = new HashSet<CampusJob>();
            this.InternJobs = new HashSet<InternJob>();
            this.ServiceJobs = new HashSet<ServiceJob>();
            this.TutorJobs = new HashSet<TutorJob>();
            this.Users = new HashSet<User>();
        }
    
        public int RegionId { get; set; }
        public string Name { get; set; }
        public string Letter { get; set; }
        public Nullable<int> ParentRegionId { get; set; }
        public Nullable<int> RootRegionId { get; set; }
        public Nullable<int> Left { get; set; }
        public Nullable<int> Right { get; set; }
        public Nullable<int> Descend { get; set; }
        public Nullable<int> Indentation { get; set; }
        public Nullable<int> Sequence { get; set; }
        public Nullable<int> ProvinceId { get; set; }
        public bool ImportReptile { get; set; }
        public bool RequireVerify { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
    
        public virtual ICollection<ActivityJob> ActivityJobs { get; set; }
        public virtual ICollection<AgentUserRegion> AgentUserRegions { get; set; }
        public virtual ICollection<CampusJob> CampusJobs { get; set; }
        public virtual ICollection<InternJob> InternJobs { get; set; }
        public virtual ICollection<ServiceJob> ServiceJobs { get; set; }
        public virtual ICollection<TutorJob> TutorJobs { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
