//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChouMei.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public Role()
        {
            this.AdminRoles = new HashSet<AdminRole>();
            this.RolePermissions = new HashSet<RolePermission>();
        }
    
        public int RoleId { get; set; }
        public string Name { get; set; }
        public Nullable<int> ParentRoleId { get; set; }
        public Nullable<int> RootRoleId { get; set; }
        public Nullable<int> Left { get; set; }
        public Nullable<int> Right { get; set; }
        public Nullable<int> Descend { get; set; }
        public Nullable<int> Indentation { get; set; }
        public Nullable<int> Sequence { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
    
        public virtual ICollection<AdminRole> AdminRoles { get; set; }
        public virtual ICollection<RolePermission> RolePermissions { get; set; }
    }
}
