//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChouMei.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class School
    {
        public School()
        {
            this.CampusJobs = new HashSet<CampusJob>();
            this.Users = new HashSet<User>();
        }
    
        public int SchoolId { get; set; }
        public string Name { get; set; }
        public int RegionId { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual ICollection<CampusJob> CampusJobs { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
