//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChouMei.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceJobPosition
    {
        public ServiceJobPosition()
        {
            this.ServiceJobs = new HashSet<ServiceJob>();
        }
    
        public int PositionId { get; set; }
        public string Name { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual ICollection<ServiceJob> ServiceJobs { get; set; }
    }
}
