//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChouMei.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trade
    {
        public long TradeId { get; set; }
        public long OrderId { get; set; }
        public Nullable<System.DateTime> DatePaid { get; set; }
        public Nullable<System.DateTime> DatePaymentConfirmed { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
