//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChouMei.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TutorJobComplain
    {
        public int ComplainId { get; set; }
        public long JobId { get; set; }
        public long UserId { get; set; }
        public int StatusId { get; set; }
        public string Description { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual ComplainStatu ComplainStatu { get; set; }
        public virtual TutorJob TutorJob { get; set; }
        public virtual User User { get; set; }
    }
}
