//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChouMei.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserFavoriteJob
    {
        public long UserId { get; set; }
        public int JobTypeId { get; set; }
        public long JobId { get; set; }
        public System.DateTime DateCreated { get; set; }
    }
}
