//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChouMei.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserCashOut
    {
        public long CashOutId { get; set; }
        public long UserId { get; set; }
        public long AccountId { get; set; }
        public decimal Amount { get; set; }
        public decimal Balance { get; set; }
        public int StatusId { get; set; }
        public string Note { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
    
        public virtual CashOutStatu CashOutStatu { get; set; }
        public virtual User User { get; set; }
        public virtual UserAccount UserAccount { get; set; }
    }
}
