//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChouMei.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_promoter_daily
    {
        public Nullable<System.DateTime> Date { get; set; }
        public int PromoterId { get; set; }
        public string PromoterName { get; set; }
        public int TeamId { get; set; }
        public string TeamName { get; set; }
        public long UserId { get; set; }
        public string UserName { get; set; }
        public string Mobile { get; set; }
        public string InvitationCode { get; set; }
        public bool Leader { get; set; }
        public Nullable<int> Total { get; set; }
    }
}
