//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChouMei.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_jobtype_jobsubtype
    {
        public int TypeId { get; set; }
        public string JobTypeName { get; set; }
        public int PositionId { get; set; }
        public string JobTypeSubName { get; set; }
    }
}
