//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChouMei.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_report_get_promoter_creator
    {
        public int PromoterId { get; set; }
        public string PromoterName { get; set; }
        public int CreatedUserId { get; set; }
        public string UserName { get; set; }
        public int CreatedUserType { get; set; }
    }
}
