// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using MeiHi.API.Models.MeiHiDistanceModelJsonTypes;

namespace MeiHi.API.Models.MeiHiDistanceModelJsonTypes
{

    public class Element
    {

        [JsonProperty("distance")]
        public Distance Distance { get; set; }

        [JsonProperty("duration")]
        public Duration Duration { get; set; }
    }

}
