// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using MeiHi.API.Models.MeiHiDistanceModelJsonTypes;

namespace MeiHi.API.Models.MeiHiDistanceModelJsonTypes
{

    public class Info
    {

        [JsonProperty("copyright")]
        public Copyright Copyright { get; set; }
    }

}
