// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using MeiHi.API.Models.MeiHiDistanceModelJsonTypes;

namespace MeiHi.API.Models
{

    public class MeiHiDistanceModel
    {

        [JsonProperty("status")]
        public int Status { get; set; }

        [JsonProperty("message")]
        public string Message { get; set; }

        [JsonProperty("info")]
        public Info Info { get; set; }

        [JsonProperty("result")]
        public Result Result { get; set; }
    }

}
